source 'https://rubygems.org'
ruby '2.2.0'

gem 'sinatra'
gem 'puma'
gem 'config_env'
gem 'rake'
gem 'rack-ssl-enforcer'
gem 'rbnacl-libsodium'
gem 'httparty'
gem 'protected_attributes'
gem 'slim'
gem 'kramdown'
gem 'jwt'
gem 'rack-flash3'
gem 'chartkick'
gem 'groupdate'
gem 'awesome_print'
gem 'activemodel'
gem 'virtus'
gem 'rack'

group :test do
  gem 'minitest'
  gem 'rack-test'
end
